'use client';
import { Navigation } from '@/components';
import FinanceContextProvider from '@/lib/store/finance-context';
import AuthContextProvider from '@/lib/store/auth-context';
import { ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';
import Head from './head';

export const metadata = {
  title: 'Finance Tracker',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <Head />
      <body>
        <AuthContextProvider>
          <FinanceContextProvider>
            <ToastContainer />
              <Navigation />
              {children}
          </FinanceContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
