'use client'

import { Navigation } from '@/components'
import FinanceContextProvider from '@/lib/store/finance-context'
import AuthContextProvider from '@/lib/store/auth-context'
import './globals.css'

export const metadata = {
  title: 'Finance Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       <AuthContextProvider>
        <FinanceContextProvider>
        <Navigation />
          {children}
        </FinanceContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  )
}
